window.EASTOKYO_ARTICLES = [
  {
    id: 1,
    section: "Weird",
    title:
      "Tokyo Announces Bold Plan to Solve Crowding by Asking Everyone to Stand Slightly More Politely",
    slug: "tokyo-polite-standing",
    image: "tokyo-skyline-main.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: true,
    popular: true,
    readingTime: 7,
    tags: ["satire", "tokyo", "weird"],
    excerpt:
      "Officials believe a modest increase in politeness could create enough emotional space for everyone.",
    body: "<p>1Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Tokyo Announces Bold Plan to Solve Crowding by Asking Everyone to Stand Slightly More Politely</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 2,
    section: "Political",
    title:
      "Committee Forms Subcommittee to Investigate Why Committees Keep Forming",
    slug: "committee-committee",
    image: "political-meeting.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 5,
    tags: ["committee", "political", "satire"],
    excerpt:
      "The first meeting has been postponed until enough committees can review it.",
    body: "<p>2Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Committee Forms Subcommittee to Investigate Why Committees Keep Forming</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 3,
    section: "Technology",
    title: "AI Tool Generates Apology Email Before Company Makes Mistake",
    slug: "ai-apology",
    image: "server-room.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 5,
    tags: ["ai", "satire", "technology"],
    excerpt:
      "The software achieved a 94% accuracy rate by studying corporate history.",
    body: "<p>3Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>AI Tool Generates Apology Email Before Company Makes Mistake</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 4,
    section: "Tokyo",
    title: "Cafe Introduces Standing Room Nap Service",
    slug: "cafe-introduces-standing-room-nap-service",
    image: "neon-street.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 4,
    tags: ["cafe", "satire", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on cafe introduces standing room nap service.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Cafe Introduces Standing Room Nap Service</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 5,
    section: "Political",
    title: "Committees forming committees",
    slug: "committees-forming-committees",
    image: "political-meeting.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 3,
    tags: ["committees", "political", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on committees forming committees.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Committees forming committees</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 6,
    section: "Technology",
    title:
      "Convenience Store Chain Adds Premium Tier for People Who Miss Their Train",
    slug: "convenience-store-chain-adds-premium-tier-for-people-who-miss-their-train",
    image: "convenience-store.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 6,
    tags: ["convenience", "satire", "technology"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on convenience store chain adds premium tier for people who miss their train.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Convenience Store Chain Adds Premium Tier for People Who Miss Their Train</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 7,
    section: "Weird",
    title: "Crows near municipal property",
    slug: "crows-near-municipal-property",
    image: "vending-machines.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 3,
    tags: ["crows", "satire", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on crows near municipal property.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Crows near municipal property</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 8,
    section: "Investigations",
    title:
      "Emergency Survey Finds 82% of Residents Pretend to Understand Ward Office Forms",
    slug: "emergency-survey-finds-82-of-residents-pretend-to-understand-ward-office-forms",
    image: "city-hall.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: true,
    readingTime: 6,
    tags: ["emergency", "investigations", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on emergency survey finds 82% of residents pretend to understand ward office forms.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Emergency Survey Finds 82% of Residents Pretend to Understand Ward Office Forms</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 9,
    section: "Culture",
    title: "Experts Warn Cherry Blossoms Becoming Too Influential",
    slug: "experts-warn-cherry-blossoms-becoming-too-influential",
    image: "shibuya-crossing.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["culture", "experts", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on experts warn cherry blossoms becoming too influential.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Experts Warn Cherry Blossoms Becoming Too Influential</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 10,
    section: "Political",
    title: "Government Launches App to Track Lost Umbrellas",
    slug: "government-launches-app-to-track-lost-umbrellas",
    image: "neon-street.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["government", "political", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on government launches app to track lost umbrellas.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Government Launches App to Track Lost Umbrellas</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 11,
    section: "Tokyo",
    title: "Has Tokyo Reached Peak Tokyo, or Is This Merely Tokyo Warming Up?",
    slug: "has-tokyo-reached-peak-tokyo-or-is-this-merely-tokyo-warming-up",
    image: "eastokyo-placeholder.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 6,
    tags: ["has", "satire", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on has tokyo reached peak tokyo, or is this merely tokyo warming up?.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Has Tokyo Reached Peak Tokyo, or Is This Merely Tokyo Warming Up?</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 12,
    section: "Investigations",
    title:
      "Inside the Secret World of People Who Actually Understand Municipal Forms",
    slug: "inside-the-secret-world-of-people-who-actually-understand-municipal-forms",
    image: "city-hall.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["inside", "investigations", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on inside the secret world of people who actually understand municipal forms.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Inside the Secret World of People Who Actually Understand Municipal Forms</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 13,
    section: "Japan",
    title: "JR-21",
    slug: "jr-21-platform-rumor-index",
    image: "eastokyo-placeholder.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 3,
    tags: ["japan", "jr", "satire"],
    excerpt: "Eastokyo's civic monitors file a satirical dispatch on jr-21.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>JR-21</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 14,
    section: "Political",
    title:
      "Lawmakers Promise Historic Reform Immediately After Lunch, Possibly Next Fiscal Year",
    slug: "lawmakers-promise-historic-reform-immediately-after-lunch-possibly-next-fiscal-year",
    image: "diet-building.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["lawmakers", "political", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on lawmakers promise historic reform immediately after lunch, possibly next fiscal year.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Lawmakers Promise Historic Reform Immediately After Lunch, Possibly Next Fiscal Year</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 15,
    section: "Weird",
    title: "Lost Umbrella Returns Changed",
    slug: "lost-umbrella-returns-changed",
    image: "neon-street.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 3,
    tags: ["lost", "satire", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on lost umbrella returns changed.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Lost Umbrella Returns Changed</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 16,
    section: "Weird",
    title: "Mascot Denies Mayoral Ambition",
    slug: "mascot-denies-mayoral-ambition",
    image: "shibuya-crossing.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 3,
    tags: ["mascot", "satire", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on mascot denies mayoral ambition.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Mascot Denies Mayoral Ambition</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 17,
    section: "Weird",
    title: "Mascot Denies Rumors of Mayoral Ambition",
    slug: "mascot-denies-rumors-of-mayoral-ambition",
    image: "shibuya-crossing.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["mascot", "satire", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on mascot denies rumors of mayoral ambition.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Mascot Denies Rumors of Mayoral Ambition</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 18,
    section: "Technology",
    title:
      "Nation Briefly United by Train Delay Apology More Detailed Than Most Novels",
    slug: "nation-briefly-united-by-train-delay-apology-more-detailed-than-most-novels",
    image: "train-platform.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 6,
    tags: ["nation", "satire", "technology"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on nation briefly united by train delay apology more detailed than most novels.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Nation Briefly United by Train Delay Apology More Detailed Than Most Novels</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 19,
    section: "Culture",
    title:
      "New Lifestyle Trend Encourages Citizens to Romanticize Being Extremely Busy",
    slug: "new-lifestyle-trend-encourages-citizens-to-romanticize-being-extremely-busy",
    image: "neon-street.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["culture", "new", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on new lifestyle trend encourages citizens to romanticize being extremely busy.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>New Lifestyle Trend Encourages Citizens to Romanticize Being Extremely Busy</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 20,
    section: "Political",
    title:
      "Official Statement Clarifies Previous Clarification Was Not Official",
    slug: "official-statement-clarifies-previous-clarification-was-not-official",
    image: "press-conference.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["official", "political", "satire"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on official statement clarifies previous clarification was not official.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Official Statement Clarifies Previous Clarification Was Not Official</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 21,
    section: "Technology",
    title:
      "One Perfectly Folded Train Etiquette Poster Solves Nothing Beautifully",
    slug: "one-perfectly-folded-train-etiquette-poster-solves-nothing-beautifully",
    image: "train-platform.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["one", "satire", "technology"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on one perfectly folded train etiquette poster solves nothing beautifully.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>One Perfectly Folded Train Etiquette Poster Solves Nothing Beautifully</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 22,
    section: "Tokyo",
    title:
      "Pedestrians Accidentally Create Parliamentary System at Shibuya Crossing",
    slug: "pedestrians-accidentally-create-parliamentary-system-at-shibuya-crossing",
    image: "eastokyo-placeholder.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["pedestrians", "satire", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on pedestrians accidentally create parliamentary system at shibuya crossing.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Pedestrians Accidentally Create Parliamentary System at Shibuya Crossing</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 23,
    section: "Tokyo",
    title:
      "Researchers Confirm Tokyo Can Fit Three More People Per Square Meter If Everyone Gives Up Hope",
    slug: "researchers-confirm-tokyo-can-fit-three-more-people-per-square-meter-if-everyone-gives-up-hope",
    image: "eastokyo-placeholder.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 7,
    tags: ["researchers", "satire", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on researchers confirm tokyo can fit three more people per square meter if everyone gives up hope.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Researchers Confirm Tokyo Can Fit Three More People Per Square Meter If Everyone Gives Up Hope</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 24,
    section: "Technology",
    title: "Robot Refuses Promotion After Learning Managerial Responsibilities",
    slug: "robot-refuses-promotion-after-learning-managerial-responsibilities",
    image: "robot.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["robot", "satire", "technology"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on robot refuses promotion after learning managerial responsibilities.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Robot Refuses Promotion After Learning Managerial Responsibilities</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 25,
    section: "Tokyo",
    title: "Salaryman Discovers Third Emotion During Commute",
    slug: "salaryman-discovers-third-emotion-during-commute",
    image: "train-platform.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["salaryman", "satire", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on salaryman discovers third emotion during commute.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Salaryman Discovers Third Emotion During Commute</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 26,
    section: "Tokyo",
    title:
      "Shibuya Crossing Temporarily Achieves Sentience, Immediately Opens Pop-Up Cafe",
    slug: "shibuya-crossing-temporarily-achieves-sentience-immediately-opens-pop-up-cafe",
    image: "shibuya-crossing.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["satire", "shibuya", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on shibuya crossing temporarily achieves sentience, immediately opens pop-up cafe.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Shibuya Crossing Temporarily Achieves Sentience, Immediately Opens Pop-Up Cafe</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 27,
    section: "Technology",
    title: "Startup Raises ¥4 Billion to Reinvent Waiting in Line",
    slug: "startup-raises-yen4-billion-to-reinvent-waiting-in-line",
    image: "business-district.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["satire", "startup", "technology"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on startup raises ¥4 billion to reinvent waiting in line.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Startup Raises ¥4 Billion to Reinvent Waiting in Line</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 28,
    section: "Weird",
    title: "Temple Cat Accepts Interim Tourism Role",
    slug: "temple-cat-accepts-interim-tourism-role",
    image: "temple-cat.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["satire", "temple", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on temple cat accepts interim tourism role.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Temple Cat Accepts Interim Tourism Role</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 29,
    section: "Weird",
    title: "Temple Cat Accepts New Role as Unofficial Tourism Minister",
    slug: "temple-cat-accepts-new-role-as-unofficial-tourism-minister",
    image: "temple-cat.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["satire", "temple", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on temple cat accepts new role as unofficial tourism minister.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Temple Cat Accepts New Role as Unofficial Tourism Minister</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 30,
    section: "Tokyo",
    title: "Tokyo Cafe Introduces Standing Room Nap Service",
    slug: "tokyo-cafe-introduces-standing-room-nap-service",
    image: "neon-street.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 4,
    tags: ["satire", "tokyo"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on tokyo cafe introduces standing room nap service.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Tokyo Cafe Introduces Standing Room Nap Service</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 31,
    section: "Technology",
    title: "Train apologies of literary merit",
    slug: "train-apologies-of-literary-merit",
    image: "server-room.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 3,
    tags: ["satire", "technology", "train"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on train apologies of literary merit.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Train apologies of literary merit</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 32,
    section: "Weird",
    title: "Umbrellas with unclear intentions",
    slug: "umbrellas-with-unclear-intentions",
    image: "neon-street.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 3,
    tags: ["satire", "umbrellas", "weird"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on umbrellas with unclear intentions.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Umbrellas with unclear intentions</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
  {
    id: 33,
    section: "Political",
    title: "Vending Machine Seen Blinking Morse Code During Cabinet Reshuffle",
    slug: "vending-machine-seen-blinking-morse-code-during-cabinet-reshuffle",
    image: "vending-machines.jpg",
    author: "Eastokyo Staff",
    date: "2026-07-08",
    featured: false,
    popular: false,
    readingTime: 5,
    tags: ["political", "satire", "vending"],
    excerpt:
      "Eastokyo's civic monitors file a satirical dispatch on vending machine seen blinking morse code during cabinet reshuffle.",
    body: "<p>Eastokyo correspondents confirmed the situation after several minutes of grave observation, two vending-machine coffees, and one unnecessary laminated notice.</p>\n    <p>The story, titled <strong>Vending Machine Seen Blinking Morse Code During Cabinet Reshuffle</strong>, has already prompted officials, commuters, and at least one deeply invested mascot to request a calmer explanation.</p>\n    <p>Analysts described the development as extremely Tokyo: practical, ceremonial, and somehow already scheduled for a follow-up meeting.</p>\n    <blockquote>\n      Satire remains the only public service currently operating ahead of schedule.\n    </blockquote>\n    <p>Further updates will be issued once the newsroom locates the correct stamp, folder, and emotionally appropriate umbrella.</p>",
  },
];

function getFeaturedArticle() {
  return (
    EASTOKYO_ARTICLES.find((article) => article.featured) ||
    EASTOKYO_ARTICLES[0]
  );
}

function getPopularArticles() {
  return EASTOKYO_ARTICLES.filter((article) => article.popular);
}

function getArticlesBySection(section) {
  return EASTOKYO_ARTICLES.filter(
    (article) =>
      article.section.toLowerCase() === String(section || "").toLowerCase()
  );
}

function getArticle(slug) {
  return EASTOKYO_ARTICLES.find((article) => article.slug === slug);
}

function randomArticle() {
  return EASTOKYO_ARTICLES[
    Math.floor(Math.random() * EASTOKYO_ARTICLES.length)
  ];
}
