import type { Metadata } from "next";
import Link from "next/link";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "When One Angle Wasn't Enough.",
  description: "Picasso, Cubism, and the moment one point of view stopped being enough.",
  alternates: { canonical: "/when-one-point-of-view-wasnt-enough" },
  robots: { index: false, follow: false, googleBot: { index: false, follow: false } },
};

const Picture = ({ desktop, mobile, alt, priority = false }: { desktop: string; mobile: string; alt: string; priority?: boolean }) => (
  <picture><source media="(max-width: 760px)" srcSet={mobile} /><img src={desktop} alt={alt} fetchPriority={priority ? "high" : undefined} loading={priority ? "eager" : "lazy"} /></picture>
);

export default function CubismStoryPage() {
  return <main id="top" className={styles.page}>
    <header className={styles.folio}><Link href="/" className={styles.brand}>EASTOKYO</Link><span className={styles.folioCenter}>IDEAS · PICASSO / CUBISM</span><span className={styles.folioRight}>ISSUE 01 · STORY 03</span></header>
    <section className={styles.hero} aria-labelledby="story-title">
      <div className={styles.heroImage}><Picture desktop="/images/editorial/cubism-orange-portrait-hero-desktop.png" mobile="/images/editorial/cubism-orange-portrait-hero-mobile.png" alt="Cubist portrait against an orange field" priority /><span className={styles.heroNumber}>03</span></div>
      <div className={styles.heroCopy}><p className={styles.kicker}>PICASSO · CUBISM · SEVERAL ANSWERS AT ONCE</p><h1 id="story-title">WHEN ONE ANGLE<em>WASN&apos;T ENOUGH.</em></h1><p className={styles.deck}>The picture stopped behaving like a window. A face could arrive from the front, the side, and somewhere in between.</p><p className={styles.byline}>WORDS · EASTOKYO<br />TOKYO · 2026</p></div>
    </section>
    <section className={styles.intro}><div className={styles.introLabel}>01 · THE FIRST CRACK</div><p className={styles.standfirst}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere, augue sed tempor dictum, massa justo feugiat nisl, vitae tristique arcu ligula vitae est.</p><aside className={styles.introAside}>One object.<br />Several positions.</aside></section>
    <section className={styles.firstBeat}><div className={styles.firstCopy}><span className={styles.beatNo}>01</span><div className={styles.prose}><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt velit at posuere bibendum. Curabitur tincidunt, eros vitae luctus consequat, erat dui feugiat dui, at pellentesque sapien nisi sit amet lacus.</p><p>Nam interdum turpis non ante rhoncus, vitae dictum est consequat. Vestibulum feugiat orci nec semper sollicitudin.</p></div></div><figure className={styles.mainFigure}><Picture desktop="/images/editorial/cubism-split-face-main-desktop.png" mobile="/images/editorial/cubism-split-face-main-mobile.png" alt="Cubist seated figure shown through overlapping facial viewpoints" /><figcaption>01 · SEVERAL POSITIONS · PABLO PICASSO</figcaption></figure></section>
    <section className={styles.fracture}><div className={styles.fractureInner}><figure className={styles.smallFigure}><Picture desktop="/images/editorial/cubism-monochrome-study-support-desktop.png" mobile="/images/editorial/cubism-monochrome-study-support-mobile.png" alt="Monochrome Cubist ink and wash study" /><figcaption>02 · STUDY</figcaption></figure><div className={styles.fractureCopy}><blockquote>A face could turn toward you and away from you <em>at the same time.</em></blockquote><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Morbi pellentesque augue nec tellus vestibulum, vitae consequat magna posuere.</p></div></div></section>
    <section className={styles.construction}><div className={styles.readingBlock}><p className={styles.sectionKicker}>02 · THE PICTURE CHANGES THE RULES</p><h2>It stops pretending to be a window.</h2><div className={styles.prose}><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus tortor vel massa accumsan, et porttitor neque egestas. Praesent sed orci sed justo luctus tincidunt.</p><p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Donec feugiat, sem at pulvinar luctus, justo neque malesuada turpis.</p></div></div><figure className={styles.climax}><Picture desktop="/images/editorial/cubism-collage-figure-main-desktop.png" mobile="/images/editorial/cubism-collage-figure-main-mobile.png" alt="Cubist collage figure built from layered geometric forms" /><figcaption>03 · CONSTRUCTION / COLLAGE · PABLO PICASSO</figcaption></figure></section>
    <section className={styles.pause}><p className={styles.pauseLabel}>A SMALL INTERRUPTION</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere consectetur est at lobortis. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p></section>
    <section className={styles.study}><figure className={styles.studyFigure}><Picture desktop="/images/editorial/cubism-pencil-head-support-desktop.png" mobile="/images/editorial/cubism-pencil-head-support-mobile.png" alt="Cubist pencil head study on aged paper" /><figcaption>04 · PENCIL HEAD STUDY · PABLO PICASSO</figcaption></figure><div className={styles.studyCopy}><p className={styles.sectionKicker}>03 · THE EYE KEEPS MOVING</p><h2>Recognition is only the beginning.</h2><div className={styles.prose}><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas faucibus mollis interdum. Donec sed odio dui. Aenean lacinia bibendum nulla sed consectetur.</p><p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Nulla vitae elit libero, a pharetra augue.</p></div></div></section>
    <section className={styles.finalAct}><div className={styles.finalCopy}><p className={styles.sectionKicker}>04 · STILL HUMAN</p><h2>Break the picture.<br />Keep the person.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur blandit tempus porttitor. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p></div><figure className={styles.finalFigure}><Picture desktop="/images/editorial/cubism-mother-child-main-desktop.png" mobile="/images/editorial/cubism-mother-child-main-mobile.png" alt="Cubist mother and child in vivid orange, blue, and green" /><figcaption>05 · FIGURE GROUP · PABLO PICASSO</figcaption></figure></section>
    <section className={styles.ending}><p>ONE VIEW WAS NEVER GOING TO BE ENOUGH.</p><span>PICASSO · CUBISM · EASTOKYO ISSUE 01</span></section>
    <footer className={styles.footer}><Link href="/">EASTOKYO</Link><a href="#top">BACK TO TOP ↑</a></footer>
  </main>;
}
