import type { Metadata } from "next";
import Link from "next/link";
import styles from "./page.module.css";
import polish from "./polish.module.css";

export const metadata: Metadata = {
  title: "Rien n’est jamais tout à fait ce qu’on croit.",
  description: "Picasso, objets, portraits, rayures, céramiques, et le plaisir de partir d’un truc pour finir ailleurs.",
  alternates: { canonical: "/nothing-is-just-what-it-is" },
  robots: { index: false, follow: false, googleBot: { index: false, follow: false } },
};

const entries = [
  { number: "01", section: "OBJET", title: "UN VÉLO DEVIENT UN TAUREAU.", image: "object", alt: "La Tête de taureau de Picasso, assemblée à partir d’une selle et d’un guidon de vélo, projette une longue ombre sur le mur de la galerie.", copy: [
    "Deux pièces de vélo posées là. Une selle et un guidon. Séparément, y a rien de mystérieux, dans un tas de ferraille vous seriez même passé devant sans les voir. Puis Picasso les met face à face et d’un coup il est là : un taureau.",
    "Toute l’astuce est là-dedans, et c’est pour ça que l’objet arrête encore les gens presque cent ans après. La selle arrête jamais d’être une selle, le guidon non plus. Picasso essaie pas de les déguiser, ni d’effacer d’où ils viennent. On voit les deux choses en même temps, et le regard passe de l’une à l’autre, vélo, taureau, vélo, taureau. Le cerveau accroche et a aucune envie de lâcher, un peu comme quand on apprend le vrai sens d’un mot et qu’on se met à l’entendre partout pendant un mois.",
    "Ce qui me plaît surtout c’est le peu qu’il a fallu faire. Deux objets tournés l’un vers l’autre, pas de colle, pas de peinture, pas d’histoire compliquée pour nous expliquer pourquoi on devrait trouver ça génial. Et pourtant ce bout de vélo contient soudain beaucoup plus qu’il y a cinq secondes. Ou alors c’est l’inverse. Peut-être que le taureau était déjà là depuis le début, planqué dans la courbe de la selle et l’écartement du guidon, et que Picasso a juste été le premier à le voir.",
    "Une fois qu’on vous a montré un truc pareil, c’est foutu, y a plus moyen de revenir en arrière. On se met à regarder les objets ordinaires d’un peu plus près et à moins faire confiance à la première idée qu’on s’en fait. Selon l’état de votre tiroir à bordel ça peut être un cadeau ou devenir carrément pénible."
  ]},
  { number: "02", section: "PORTRAIT", title: "LA SYMÉTRIE N’A JAMAIS ÉTÉ LE SUJET.", image: "portrait", alt: "Un portrait peint fragmenté, composé de plans anguleux, de contours marqués et d’une coiffe sculpturale.", copy: [
    "Un visage est censé se tenir correctement. Deux yeux à peu près au même niveau, un nez au milieu, une bouche juste en dessous, pile là où quelques milliers d’années de biologie ont décidé de la mettre. Pas de fantaisie merci. Picasso, disons-le, en avait rien à faire des convenances.",
    "Un œil se balade. Un nez s’allonge comme s’il essayait de voir ce qui se passe à l’autre bout de la pièce. Le visage entier explose en plans et en angles qui normalement ont rien à faire ensemble. Et pourtant, et ça continue de me surprendre, la personne disparaît pas derrière tout ça. Elle est toujours là, toujours elle-même, parfaitement reconnaissable, même avec un nez parti dans une aventure qu’aucun nez n’avait sérieusement envisagée jusque-là.",
    "Jusqu’où on peut transformer un visage avant qu’il cesse d’être le même ? Apparemment beaucoup plus loin qu’on le pense. On aime imaginer l’identité comme un truc fragile, comme si bouger assez de choses à l’extérieur finissait forcément par faire sortir la personne par la porte de derrière. Mais même en dehors d’un tableau ça marche pas comme ça. L’âge nous change, le chagrin aussi. Tomber amoureux nous change, arrêter de l’être également, en général avec moins d’élégance. On peut regarder une photo de soi prise vingt ans plus tôt, comprendre même plus ce qu’on essayait de faire avec cette coupe de cheveux, et sentir quand même, quelque part au fond, que oui c’était bien nous. Ça l’a toujours été, choix vestimentaires douteux compris.",
    "Picasso pousse juste cette élasticité beaucoup plus loin, et beaucoup plus vite, que la vie de tous les jours prend la peine de le faire. Et pourtant le portrait tient toujours. Être soi-même a peut-être jamais consisté à garder chaque détail exactement à sa place. Y a peut-être beaucoup plus d’espace là-dedans qu’on le croit."
  ]},
  { number: "03", section: "RAYURES", title: "PAUL SMITH Y MET SA PATTE.", image: "stripes", alt: "Une installation textile rayée suspendue au-dessus de la galerie en vagues superposées de lumière et d’ombre.", copy: [
    "Là, la transformation est d’un tout autre genre, parce que personne touche au Picasso lui-même. Paul Smith change ce qu’il y a autour. De la couleur, des motifs, des rayures qui filent dans tous les sens comme si elles étaient déjà en retard. L’œuvre reste exactement là où elle était, pas un coup de pinceau a bougé, et pourtant elle se retrouve balancée dans une conversation à laquelle elle avait jamais demandé à participer.",
    "Et ça change tout ce qu’on remarque. Une couleur dans la toile se réveille parce que le mur d’à côté parle soudain la même langue. Une forme se met à répondre à une autre, à l’autre bout de la salle. Un truc qu’on aurait à peine remarqué devient impossible à quitter des yeux. Rien a changé dans le tableau et malgré tout le tableau a complètement changé. Si ça vous paraît contradictoire, voyez ça avec le mur.",
    "C’est le contexte qui fait le boulot. On aime croire que la valeur habite pour de bon à l’intérieur des choses, utile ici, inutile là, beau, moche, important, oubliable, comme si chaque objet sortait de l’usine avec son étiquette collée dessus pour toujours. Mais prenez exactement le même objet et bougez-le. Changez la pièce, la lumière, ce qui l’entoure, l’histoire qui arrive avec, et regardez à quelle vitesse notre jugement se met lui aussi à bouger.",
    "Une selle montée sur un vélo est utile. La même selle abandonnée dans le caniveau devient un déchet que personne a envie de ramasser. Placez-la sous un guidon, entre les bonnes mains, et voilà des gens qui traversent des océans pour venir la regarder, la prendre en photo et repartir avec la carte postale. La matière est pas devenue plus intelligente pendant la nuit. C’est nous qui avons changé d’avis sur ce qui compte."
  ]},
  { number: "04", section: "CÉRAMIQUES", title: "PICASSO NE FINISSAIT JAMAIS SON ASSIETTE.", image: "ceramics", alt: "Un mur de galerie couvert d’assiettes en céramique, avec des visages peints et des motifs parmi les rangées d’assiettes blanches.", copy: [
    "Une assiette connaît déjà son métier. On met le dîner dessus, on mange, terminé. Y a normalement pas grand-chose à ajouter. Puis Picasso lui donne un visage. Une cruche se retrouve avec un corps. L’argile arrête d’être seulement ce truc dans lequel on mange ou on boit et devient une surface à gratter, peindre, tordre, déformer, voire à engueuler à trois heures du matin si besoin. Un objet fait pour être utile se retrouve avec une deuxième vie qu’il avait absolument pas demandée.",
    "Je pense pas que Picasso ait jamais voulu nous faire croire que l’assiette avait secrètement jamais été une assiette. Bien sûr que si. C’est justement ce qui rend le truc drôle. Sauf que « assiette » était pas forcément la fin de la phrase, et on découvre assez vite que c’est vrai pour plein de choses.",
    "Ce qui finit par ressembler pas mal à Picasso lui-même. Peintre, évidemment, et pas exactement un peintre discret, l’un des types les plus célèbres à avoir jamais tenu un pinceau. On pourrait s’arrêter là, dossier classé. Sauf que même cette définition finit par être trop petite pour lui. Sculpture, céramique, gravure, collage, peu importait le matériau, du moment qu’il attirait son attention et lui offrait un nouveau problème assez intéressant pour l’occuper cette semaine-là.",
    "Y a un côté presque rebelle à refuser de laisser sa propre réussite refermer la porte derrière soi. On devient bon dans un truc, les gens le remarquent, vous récompensent encore et encore, et à un moment les applaudissements commencent à ressembler moins à un compliment qu’à une consigne : reste ici, bouge surtout pas, c’est exactement comme ça qu’on t’aime. Picasso, lui, continuait à aller voir ailleurs, une céramique sous le bras, sans avoir l’air spécialement inquiet.",
    "C’est peut-être aussi ça une forme de liberté : pas fuir ce qu’on est, mais refuser que ça devienne une cage, même avec une très belle vue. Oui c’est moi. Mais non c’est pas tout ce que je serai."
  ]},
];

function Picture({ name, alt, eager = false }: { name: string; alt: string; eager?: boolean }) { return <picture className={styles.picture}><source media="(max-width: 780px)" srcSet={`/images/editorial/index-${name}-mobile.jpg`} /><img src={`/images/editorial/index-${name}-desktop.jpg`} alt={alt} loading={eager ? "eager" : "lazy"} fetchPriority={eager ? "high" : undefined} decoding="async" /></picture>; }

export default function PicassoIndexStoryPage() { return <main className={`${styles.page} ${polish.page}`} id="top">
<header className={styles.folio}><Link className={styles.brand} href="/">EASTOKYO</Link><span className={styles.folioCenter}>INDEX · NUMÉRO 01</span><span className={styles.folioRight}>TOKYO · SEPTEMBRE 2026</span></header>
<section className={styles.hero} aria-labelledby="index-title"><Picture name="hero" alt="" eager /><div className={styles.heroShade} aria-hidden="true"/><div className={styles.heroNumber} aria-hidden="true">05</div><div className={styles.heroCopy}><p className={styles.kicker}>INDEX PICASSO · COMMENCEZ N’IMPORTE OÙ</p><h1 id="index-title">RIEN N’EST JAMAIS<br/>TOUT À FAIT CE<br/><em>QU’ON CROIT.</em></h1><p className={styles.deck}>On part d’un truc et on finit ailleurs. C’était déjà la moitié du plaisir.</p></div><div className={styles.heroNote}><span>OBJET</span><span>PORTRAIT</span><span>RAYURES</span><span>CÉRAMIQUES</span></div></section>
<section className={styles.intro}><p className={styles.introLabel}>L’INDEX</p><div className={styles.introCopy}><p>Picasso pouvait partir de n’importe quoi. Une selle de vélo. Un visage. Une assiette. Une pièce couverte de rayures du sol au plafond. Ce que c’était au départ, franchement, ça comptait pas tant que ça. Ce qui comptait c’est ce qui se passait une fois qu’il arrêtait de croire que la première réponse devait être la bonne. Parce qu’elle était bien, cette première réponse. Carrément juste, même. Oui c’est une selle de vélo. Oui c’est une assiette. C’est un visage, qu’est-ce que ça pourrait être d’autre. Sauf que Picasso avait cette manie, un peu belle et un peu têtue, de rester planté devant les choses juste assez longtemps pour qu’une deuxième question lui tape sur l’épaule.</p><p><strong>Et si c’était autre chose ?</strong></p><p>C’est pas un cours d’histoire de l’art, encore moins un défilé des grands classiques. Disons plutôt quatre portes d’entrée vers le même genre de malice : ce refus de croire qu’avoir compris ce qu’est une chose veut dire qu’on a fini de découvrir ce qu’elle peut devenir.</p></div></section>
<section className={styles.entries} aria-label="Entrées de l’index Picasso">{entries.map((entry)=><article className={styles.entry} key={entry.number}><div className={styles.entryNumber} aria-hidden="true">{entry.number}</div><div className={styles.entryMeta}><p>{entry.section}</p><span>EASTOKYO · INDEX 05</span></div><div className={styles.entryBody}><h2>{entry.title}</h2><div className={styles.entryText}>{entry.copy.map((p,i)=><p key={i}>{p}</p>)}</div></div><figure className={styles.entryFigure}><Picture name={entry.image} alt={entry.alt}/><figcaption>{entry.number} · {entry.section} / INDEX PICASSO</figcaption></figure></article>)}</section>
<section className={styles.closing}><figure className={styles.closingFigure}><Picture name="closing" alt="Une visiteuse s’arrête devant un mur de galerie couvert d’assiettes en céramique."/><figcaption>05 · REGARDEZ ENCORE.</figcaption></figure><div className={styles.closingText}><div className={styles.closingRule}>PICASSO · LA RÉALITÉ RÉARRANGÉE</div><p className={styles.closingLead}>Le but a jamais été de rendre le monde plus dur à reconnaître.</p><p className={styles.closingCopy}>Reconnaître les choses ça sert, c’est même indispensable. Il nous faut des noms, des catégories, quelques raccourcis pour traverser une journée sans avoir à interroger chaque objet qui croise notre chemin. Ça c’est une chaise. Ça c’est bon à jeter. Ça c’est beau. Cette personne a plus rien à me donner pour le moment. Très bien. Le problème a jamais été de porter ce premier jugement, il commence quand on décide qu’il est définitif.</p><p className={styles.closingCopy}>Parce qu’un truc qui paraît inutile est parfois juste dans la mauvaise pièce. Un accident peut finir bien meilleur que le plan de départ. Une idée un peu bête peut refuser de partir, traîner assez longtemps et devenir sans prévenir une excellente idée. Et quelqu’un qu’on avait rangé trop vite dans une case était peut-être pas vide du tout, c’est juste la case qui était trop petite pour tout ce qu’il y avait dedans.</p><p className={styles.closingCopy}>C’est sûrement ce que je retiens de tout ça. Picasso nous demande jamais de faire semblant que la réalité existe pas. La selle reste une selle, l’assiette reste une assiette et le visage reste un visage. Il refuse juste de laisser la réalité se poser trop vite, prendre ses aises et décider qu’elle a plus rien d’autre à nous montrer.</p><p className={styles.closingCopy}>Et c’est peut-être là que se cache le petit sourire derrière tout ça, dans cette question qui revient tranquillement à chaque fois qu’on pense avoir fini :<br/><strong>Oui d’accord. C’est ça. Et quoi d’autre ?</strong></p><p className={styles.closingLead}>AVANT DE LE JETER, REGARDEZ ENCORE.</p><p className={styles.closingCopy}><em>RIEN N’EST JAMAIS TOUT À FAIT CE QU’ON CROIT.</em></p><Link className={styles.backLink} href="/">EASTOKYO · NUMÉRO 01</Link></div></section>
</main>; }