/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Link from "next/link";
import styles from "./page.module.css";
import polish from "./polish.module.css";

export const metadata: Metadata = {
  title: "Nothing Is Just What It Is.",
  description: "We start with one thing and end up somewhere else. That’s half the pleasure.",
  alternates: { canonical: "/nothing-is-just-what-it-is" },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
  openGraph: {
    title: "Nothing Is Just What It Is.",
    description: "We start with one thing and end up somewhere else. That’s half the pleasure.",
    url: "/nothing-is-just-what-it-is",
    siteName: "EASTOKYO",
    locale: "en_US",
    type: "article",
    images: [{ url: "/images/editorial/index-hero-desktop.jpg", alt: "Nothing Is Just What It Is." }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Nothing Is Just What It Is.",
    description: "We start with one thing and end up somewhere else. That’s half the pleasure.",
    images: ["/images/editorial/index-hero-desktop.jpg"],
  },
};

const entries = [
  { number: "01", section: "OBJECT", title: "A BICYCLE BECOMES A BULL.", image: "object", alt: "Picasso’s Bull’s Head, assembled from a bicycle seat and handlebars, casts a long shadow on the gallery wall.", copy: [
    "Two bicycle parts, sitting there in the pile. Just an old seat and a bent handlebar. Separately, nothing amazing about them at all. In a pile of scrap metal you'd have walked right past. Nothing ever gets noticed. Then Picasso turns them to face each other and there it is. A bull.",
    "Picasso’s whole theory is in that, which is why the object still stops people more than eighty years later. The seat never stops being a seat. Neither does the handlebar. He doesn't disguise them or erase where they came from. We can see both things at once, and the eye keeps moving between them, bicycle, bull, bicycle, bull. Once the brain catches on, it has no intention of letting go, kind of like learning the literal meaning of a word and then hearing it everywhere for a month.",
    "What I like is how little was actually done. Two rejected objects turned toward each other. No glue or elaborate story to convince us it's so brilliant. And yet this scrap of bicycle suddenly means more than it did only five seconds earlier. Or could it be the reverse? Perhaps the bull was there all along, folded into the curve of the seat and the spread of the handlebar, and Picasso was the first to notice.",
    "Once someone has shown you a phenomenon like that, there's just no going back. You start looking more closely at ordinary objects, and trusting your first idea about them a lot less. Depending on the condition of your junk drawer, that's either a gift or something downright irritating."
  ]},
  { number: "02", section: "PORTRAIT", title: "SYMMETRY WAS NEVER THE SUBJECT.", image: "portrait", alt: "A fragmented painted portrait composed of angular planes, strong contours and a sculptural headdress.", copy: [
    "A face is supposed to hold itself within the guidelines. Two eyes roughly level, a nose belongs in the middle, then a mouth just below. Exactly where they belong. No fantasy or imagination, thank you very much. Picasso, to state the obvious, didn’t give a damn about convention.",
    "An eye wanders off, oh well. A nose stretches out as if it’s trying to smell what happened at the other end of the gallery. The entire face breaks into planes and angles that have no business sitting together on the same canvas. And it still surprises me: the person doesn't vanish behind all that. They're still there and perfectly recognisable, even with a nose that has gone off on a find the fart adventure.",
    "How far can a face be pushed before it stops being a face? Further than we think, apparently. We like to imagine identity as something very fragile, as if rearranging enough on the outside would eventually erase an identity. But even off the canvas, it doesn't work that way. Age changes us from head to toe. Grief has the same effect. Falling in love totally reinvents us, and falling out of it makes us different yet again, usually with a lot less elegance.",
    "You can look at a photo of yourself from twenty years ago, not even understand what you were doing with that haircut, and still feel, somewhere underneath it all, that yes… that really was you. Don’t deny it, polyester brown pants and red aloha shirt included.",
    "Picasso comes along and pushes that elasticity much further, and faster, than daily life wants to. The strange portrait still holds together. Being yourself was possibly never a matter of keeping every detail in the exact right place. There may be more room than we assume."
  ]},
  { number: "03", section: "STRIPES", title: "PAUL SMITH ADDS HIS TOUCH.", image: "stripes", alt: "A striped textile installation hangs above the gallery in layered waves of light and shadow.", copy: [
    "Here’s a transformation of an entirely different kind, because nobody changes the Picasso itself. Paul Smith reinvents the walls that surround it. Color and stripes running in every direction like a tiger chasing a zebra. The work stays exactly where it was, though. Not a single brushstroke is moved, but it's dropped into a conversation it never even asked to join.",
    "Which changes everything we notice. The artistic voice in the painting wakes up because the wall beside it is suddenly speaking the same language. Then a shape starts answering another one across the hallway. Something we'd barely have registered becomes impossible to look away from. Nothing in the painting has changed, and yet the painting has changed completely. If that sounds contradictory, you can talk to the wall about it.",
    "Context does all the real work. We like to believe value is trapped permanently inside things. Useful here but useless there. Beautiful or ugly. But take anything and move it somewhere else. Change the room a little and dim the lights. Move what surrounds it until the story attached to it moves too. Then watch how fast your judgment shifts.",
    "A seat mounted on a bicycle has a job to do. The same seat left in the gutter is useless garbage nobody wants to touch. Put it under a handlebar, in the right hands, and people cross oceans to look at it and leave with the postcard. The scraps of bicycle parts didn't gain intelligence overnight. We're the ones who changed our minds about what’s unique and valuable."
  ]},
  { number: "04", section: "CERAMICS", title: "PICASSO NEVER FINISHED HIS PLATE.", image: "ceramics", alt: "A gallery wall covered with ceramic plates, including painted faces and patterns among rows of white plates.", copy: [
    "A plate already knows what’s going on. You put dinner on it, then eat, done. Not much else to add, ordinarily. Then Picasso gives it a face. A jug ends up with a body. The plate stops being just the thing we eat from and becomes a surface to paint, or smash on the floor, at three in the morning. Something made for everyday use ends up with a second life or in the garbage.",
    "I don't think Picasso wanted us to forget that the plate held something special before the artistic transformation… mashed potatoes and gravy. Of course, we can’t forget: a plate that served vegetables now serves the world as a priceless artwork decades later! That's exactly what makes it so hilarious. \"Food\" wasn't anywhere near where the plate had to end, and you find out fairly quickly that the same is true in your own life.",
    "Which ends up sounding a lot like Picasso himself. A painter, obviously, and not shy at all. One of the most famous men ever to hold a paintbrush. We could stop the conversation right there. Except he eventually outgrew that definition too. He used whatever he could find and the material barely mattered because he saw true value in the ordinary. As long as it caught his attention and gave him some new problem worth a week of his time.",
    "There's something almost rebellious in refusing to let your own success close the door behind you. You become good at something, naturally, people notice, then reward you for it again and again, and at some point the applause starts sounding less like praise than an instruction: stay here and don't move, this is exactly how we like you. Picasso, meanwhile, kept wandering off to look elsewhere, a plain white plate or discarded metal scraps under his arm, seemingly worthless.",
    "That's a form of freedom too! Refusing to let reputation and success become a cage, even one with a beautiful ocean view. Yes, this is me right now. But no, it isn't all I'll be."
  ]},
];

function Picture({ name, alt, eager = false }: { name: string; alt: string; eager?: boolean }) { return <picture className={styles.picture}><source media="(max-width: 780px)" srcSet={`/images/editorial/index-${name}-mobile.jpg`} /><img src={`/images/editorial/index-${name}-desktop.jpg`} alt={alt} loading={eager ? "eager" : "lazy"} fetchPriority={eager ? "high" : undefined} decoding="async" /></picture>; }

export default function PicassoIndexStoryPage() { return <main className={`${styles.page} ${polish.page}`} id="top">
<header className={styles.folio}><Link className={styles.brand} href="/">EASTOKYO</Link><span className={styles.folioCenter}>INDEX · ISSUE 01</span><span className={styles.folioRight}>TOKYO · SEPTEMBER 2026</span></header>
<section className={styles.hero} aria-labelledby="index-title"><Picture name="hero" alt="" eager /><div className={styles.heroShade} aria-hidden="true"/><div className={styles.heroNumber} aria-hidden="true">05</div><div className={styles.heroCopy}><p className={styles.kicker}>PICASSO INDEX · START ANYWHERE</p><h1 id="index-title">NOTHING IS JUST<br/>WHAT IT <em>IS.</em></h1><p className={styles.deck}>We start with one thing and end up somewhere else. That’s half the pleasure.</p><p className={styles.byline}>WORDS & PHOTOGRAPHY: JAMES SIMMONS<br/>EASTOKYO · ISSUE 01</p></div><div className={styles.heroNote}><span>OBJECT</span><span>PORTRAIT</span><span>STRIPES</span><span>CERAMICS</span></div></section>
<section className={styles.intro}><p className={styles.introLabel}>THE INDEX</p><div className={styles.introCopy}><p>Picasso could start from anything. A bicycle seat or a plain white dinner plate. What the art was at the beginning hardly crossed anyone’s mind. What people noticed was what happened once he stopped believing the first answer had to be the right one. And the first answer was good, entirely correct even. Yes, it's a bicycle seat. A face, obviously, what else would it be. Except Picasso had this habit, stubborn and mysteriously beautiful, of standing in front of things just long enough for a second question to tap him on the shoulder.</p><p><strong>What if it was actually something else?</strong></p><p>This isn't an art history lesson, still less a parade of Picasso’s greatest hits. Instead I call it four ways into the same mischief: the refusal to believe that knowing what something is means we've finished wondering what it could be.</p></div></section>
<section className={styles.entries} aria-label="Picasso Index entries">{entries.map((entry)=><article className={styles.entry} key={entry.number}><div className={styles.entryNumber} aria-hidden="true">{entry.number}</div><div className={styles.entryMeta}><p>{entry.section}</p><span>EASTOKYO · INDEX 05</span></div><div className={styles.entryBody}><h2>{entry.title}</h2><div className={styles.entryText}>{entry.copy.map((p,i)=><p key={i}>{p}</p>)}</div></div><figure className={styles.entryFigure}><Picture name={entry.image} alt={entry.alt}/><figcaption>{entry.number} · {entry.section} / PICASSO INDEX</figcaption></figure></article>)}</section>
<section className={styles.closing}><figure className={styles.closingFigure}><Picture name="closing" alt="A visitor stops in front of a gallery wall covered with ceramic plates."/><figcaption>05 · LOOK AGAIN.</figcaption></figure><div className={styles.closingText}><div className={styles.closingRule}>PICASSO · REALITY REARRANGED</div><p className={styles.closingLead}>The point was never to make the world harder to recognise.</p><p className={styles.closingCopy}>Recognising things is essential, even mandatory. We need names and categories. Oh, that's a table and that’s a watermelon. This sock belongs in the trash. That orchid is beautiful. My ex has nothing more to give the relationship. Fine. The problem begins when a judgment stops being provisional and becomes the verdict.</p><p className={styles.closingCopy}>Because maybe something that looks useless is just in the wrong room. An accident can turn out much better than the original plan and a stupid idea can become an excellent one. And someone we threw away too quickly probably wasn’t empty at all. The box was just too small for what was inside.</p><p className={styles.closingCopy}>That's probably what I take from all this. Picasso never asks us to pretend. He only refuses to let reality forget it has a whole lot more to show us.</p><p className={styles.closingCopy}>The smile is in that… somewhere in the questions that keep resurfacing every time we think we're really done:<br/><strong>Yes, all right. That's it. And what else?</strong></p><p className={styles.closingLead}>BEFORE THROWING IT AWAY, LOOK AGAIN.</p><p className={styles.closingCopy}><em>NOTHING IS JUST WHAT IT IS.</em></p><Link className={styles.backLink} href="/">EASTOKYO · ISSUE 01</Link></div></section>
</main>; }